# Pandas

Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is one-dimensional array-like object, while a DataFrame is a two-dimensional, size mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columsn)

In [1]:
import pandas as pd

In [3]:
# Series

data = [1, 2, 3, 4, 5]

series = pd.Series(data)
print(f"Series: \n{series}")

Series:
0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
# Create a Series from Dictionary

data = {'a': 1, 'b': 2, 'c': 3, 'd': 4}
series_dict = pd.Series(data)
print(f"Series: \n{series_dict}")

Series:
a    1
b    2
c    3
d    4
dtype: int64

In [6]:
data = [10, 20, 30]
index = ['a', 'b', 'c']
pd.Series(data, index=index)

a    10
b    20
c    30
dtype: int64

### DataFrame

In [7]:
## Create a DataFrame from a dictionary of list

data = {
    'Name': ['Bhupathe', 'Veerashekar', 'Geetha'],
    'Age': [20, 24, 42],
    'City': ['Udupi', 'Surathkal', 'Chennai']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

          Name  Age       City
0     Bhupathe   20      Udupi
1  Veerashekar   24  Surathkal
2       Geetha   42    Chennai
<class 'pandas.core.frame.DataFrame'>

In [8]:
## Create a DataFrame from a list of dictionary
data = [
    {'Name': 'Bhupathe', 'Age': 20, 'City': 'Udupi'},
    {'Name': 'Chini', 'Age': 22, 'City': 22}
]

pd.DataFrame(data)

       Name  Age   City
0  Bhupathe   20  Udupi
1     Chini   22     22

In [12]:
df = pd.read_csv('Sales-Export_2019-2020.csv')
df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,"17,524.02",14122.61,2/12/2020,Books,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,70-0511466
1,Finland,"116,563.40",92807.78,9/26/2019,Games,Hilll-Vandervort,Hube Corey,Wat Bowkley,Mobile,28-6585323
2,Portugal,"296,465.56",257480.34,7/11/2019,Clothing,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,PC,58-7703341
3,Portugal,"74,532.02",59752.32,4/2/2020,Beauty,Hessel-Stiedemann,Celine Tumasian,Aurelie Wren,PC,14-6700183
4,Spain,"178,763.42",146621.76,12/22/2019,Games,Johns and Sons,Emalia Dinse,Bertha Walbrook,Tablet,15-8765160

In [34]:
data = {
    'Name': ['Bhupathe', 'Veerashekar', 'Geetha'],
    'Age': [20, 24, 42],
    'City': ['Udupi', 'Surathkal', 'Chennai']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

          Name  Age       City
0     Bhupathe   20      Udupi
1  Veerashekar   24  Surathkal
2       Geetha   42    Chennai
<class 'pandas.core.frame.DataFrame'>

In [14]:
df['Name']

0       Bhupathe
1    Veerashekar
2         Geetha
Name: Name, dtype: object

In [ ]:
## Row Access
df.loc[1]

Name    Veerashekar
Age              24
City      Surathkal
Name: 1, dtype: object

In [ ]:
## Column Acessing
df.iloc[1]

Name    Veerashekar
Age              24
City      Surathkal
Name: 1, dtype: object

In [17]:
# df.loc[0][0]
df.iloc[0][0]

C:\Users\BHUPATHE\AppData\Local\Temp\ipykernel_26268\1819246170.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]

'Bhupathe'

In [20]:
df

          Name  Age       City
0     Bhupathe   20      Udupi
1  Veerashekar   24  Surathkal
2       Geetha   42    Chennai

In [19]:
## Accessing a spedified element
df.at[1, 'Age']

np.int64(24)

In [21]:
df.at[1, 'Name']

'Veerashekar'

In [22]:
df.at[0, 'Name']

'Bhupathe'

In [27]:
## Accessing a specified element usin iat
df.iat[2, 2] # [row index, column index]

'Chennai'

### Data Manipulation

In [35]:
df

          Name  Age       City
0     Bhupathe   20      Udupi
1  Veerashekar   24  Surathkal
2       Geetha   42    Chennai

In [36]:
df['Salary'] = [50000, 45000, 40000]
df

          Name  Age       City  Salary
0     Bhupathe   20      Udupi   50000
1  Veerashekar   24  Surathkal   45000
2       Geetha   42    Chennai   40000

In [37]:
## Remove a column
df.drop('Salary', axis = 1) # 1 is for column and 0 for row(default)

          Name  Age       City
0     Bhupathe   20      Udupi
1  Veerashekar   24  Surathkal
2       Geetha   42    Chennai

In [38]:
df

          Name  Age       City  Salary
0     Bhupathe   20      Udupi   50000
1  Veerashekar   24  Surathkal   45000
2       Geetha   42    Chennai   40000

In [39]:
# df = df.drop('Salary', axis=1)
df.drop('Salary', axis=1, inplace = True)

In [40]:
df

          Name  Age       City
0     Bhupathe   20      Udupi
1  Veerashekar   24  Surathkal
2       Geetha   42    Chennai

In [41]:
## Add age to the column
df['Age'] = df['Age'] + 5
df

          Name  Age       City
0     Bhupathe   25      Udupi
1  Veerashekar   29  Surathkal
2       Geetha   47    Chennai

In [42]:
df.drop(0, inplace=True)

In [43]:
df

          Name  Age       City
1  Veerashekar   29  Surathkal
2       Geetha   47    Chennai

In [44]:
df = pd.read_csv('Sales-Export_2019-2020.csv')
df.head()

,country,order_value_EUR,cost,date,category,customer_name,sales_manager,sales_rep,device_type,order_id
0,Sweden,"17,524.02",14122.61,2/12/2020,Books,Goldner-Dibbert,Maxie Marrow,Madelon Bront,Mobile,70-0511466
1,Finland,"116,563.40",92807.78,9/26/2019,Games,Hilll-Vandervort,Hube Corey,Wat Bowkley,Mobile,28-6585323
2,Portugal,"296,465.56",257480.34,7/11/2019,Clothing,Larkin-Collier,Celine Tumasian,Smitty Culverhouse,PC,58-7703341
3,Portugal,"74,532.02",59752.32,4/2/2020,Beauty,Hessel-Stiedemann,Celine Tumasian,Aurelie Wren,PC,14-6700183
4,Spain,"178,763.42",146621.76,12/22/2019,Games,Johns and Sons,Emalia Dinse,Bertha Walbrook,Tablet,15-8765160

In [45]:
## Display the data types of each column
print(f"Data Types:\n {df.dtypes}")

Data Types:
 country               object
 order_value_EUR      object
 cost                float64
date                  object
category              object
customer_name         object
sales_manager         object
sales_rep             object
device_type           object
order_id              object
dtype: object

In [46]:
## Describe the DataFrame
print(f"Statistical Summary:\n{df.describe()}")

Statistical Summary:
               cost
count    1000.000000
mean    94369.310990
std     51540.020934
min     12113.680000
25%     54247.957500
50%     87094.760000
75%    125570.837500
max    304701.430000

In [48]:
## Group by a column and perform an aggregation
grouped = df.groupby('category')['Value'].mean()
print(f'Mean value by category:\n {grouped}')

KeyError: 'Column not found: Value'