# Handling Imbalanced Dataset

Suppose you have 1000 dataset. Consider this data is binary categorical data. In this data 900 data are yes and remaining 100 is no. If we see the ratio of this,

900 : 100 = 9 : 1 ---> Imbalanced data

To Handle this kind of problems there are two techniques,

1. Up Sampling
2. Down Sampling

In [1]:
import numpy as np
import pandas as pd

In [4]:
# Set the random seed for reproductivity
np.random.seed(123)

# Creata a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [10]:
## Create my dataframe with imbalanced dataset
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale = 1, size = n_class_0),
    'feature_2': np.random.normal(loc=0, scale = 1, size = n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale = 1, size = n_class_1),
    'feature_2': np.random.normal(loc=2, scale = 1, size = n_class_1),
    'target': [1] * n_class_1
})

In [11]:
df = pd.concat([class_0, class_1]).reset_index(drop=True)

In [12]:
df.head()

   feature_1  feature_2  target
0  -0.650884   1.375188       0
1   2.079573   0.524683       0
2   1.445297   0.230819       0
3  -0.668054   0.127475       0
4  -0.581201  -1.441303       0

In [13]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

### Up Sampling

In [14]:
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [15]:
from sklearn.utils import resample

df_minority_upsampled = resample(
    df_minority,
    replace = True, ## Sample with replacement
    n_samples = len(df_majority),
    random_state = 42
)

In [17]:
df_minority_upsampled.shape

(900, 3)

In [18]:
df_upsampled = pd.concat([df_majority, df_minority_upsampled])
df_upsampled.head()

   feature_1  feature_2  target
0  -0.650884   1.375188       0
1   2.079573   0.524683       0
2   1.445297   0.230819       0
3  -0.668054   0.127475       0
4  -0.581201  -1.441303       0

In [20]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

### Down Sampling

In [21]:
# Set the random seed for reproductivity
np.random.seed(123)

# Creata a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

## Create my dataframe with imbalanced dataset
class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale = 1, size = n_class_0),
    'feature_2': np.random.normal(loc=0, scale = 1, size = n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale = 1, size = n_class_1),
    'feature_2': np.random.normal(loc=2, scale = 1, size = n_class_1),
    'target': [1] * n_class_1
})

df = pd.concat([class_0, class_1]).reset_index(drop=True)

df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [22]:
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [23]:
from sklearn.utils import resample

df_majority_downsampled = resample(
    df_majority,
    replace = False, ## Sample without replacement
    n_samples = len(df_minority),
    random_state = 42
)

In [25]:
df_majority_downsampled.shape

(100, 3)

In [26]:
df_downsampled = pd.concat([df_majority_downsampled, df_minority])
df_downsampled.head()

     feature_1  feature_2  target
70    0.468439   1.720920       0
827   1.089165  -0.464899       0
231   0.753869  -0.969798       0
588   0.588686  -0.704720       0
39    0.283627   1.012868       0

In [27]:
df_downsampled.target.value_counts()

target
0    100
1    100
Name: count, dtype: int64