## Data Encoding

1. Nominal/OHE Encoding
2. Label and Ordinal Encoding
3. Target Guided Ordinal Encoding

### Nominal/OHE Encoding

One hot encoding, also as nominal encoding, is a technique used to reqresent categorical data as numerical data, which is more suitable for machine learning algorithms. In this technique, each category is represented as a binary vector where each bit corresponds to a unique category. For example, if we have a categorical variable 'color' with possible values (red, green, blue) we can represent it using one hot encoding as follows:

1. Red: [1, 0, 0]
2. Green: [0, 1, 0]
3. Blue: [0, 0, 1]

In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
## Create a dataframe
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'red', 'blue']
})

In [3]:
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [4]:
## create a instance of OneHotEncoder
encoder = OneHotEncoder()

In [12]:
## 2 Dimension
df[['color']]

   color
0    red
1   blue
2  green
3    red
4   blue

In [14]:
## 1 Dimension
df['color']

0      red
1     blue
2    green
3      red
4     blue
Name: color, dtype: object

In [18]:
encoded = encoder.fit_transform(df[['color']]).toarray() 
## alphabet sorting, [[blue, green, red]]

In [19]:
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [22]:
encoder_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out())
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0

In [23]:
## for new data
encoder.transform([['red']]).toarray()

d:\Udemy Courses\complete_data_science_machine_learning_dl_nlp_bootcamp\.venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 1.]])

In [25]:
pd.concat([df, encoder_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3    red         0.0          0.0        1.0
4   blue         1.0          0.0        0.0

##### Assignment

In [28]:
import seaborn as sns
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

### Label Encoding

Label encoding and ordinal encoding are tow techniques used to encode categorical data as numerical data.\
Label encoding involves assigning a unique numerical label to each category in the variable. The labels are usually assigned in alphabetical order or based on the frequency of the categories. For example, if we have a categorical variable 'color' with three possible values (red, green, blue), we can prepresent it using label encoding as follows:

1. Red: 1
2. Green: 2
3. Blue: 3

In [29]:
## Create a dataframe
df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'red', 'blue']
})

In [30]:
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [31]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder = LabelEncoder()

In [32]:
lbl_encoder.fit_transform(df[['color']])

d:\Udemy Courses\complete_data_science_machine_learning_dl_nlp_bootcamp\.venv\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 2, 0])

In [33]:
lbl_encoder.transform([['red']])

d:\Udemy Courses\complete_data_science_machine_learning_dl_nlp_bootcamp\.venv\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

all the above categories like color (red, green, blue) are nominal values/categories. Meaning is that the encoding done to the values doesn't mean that higher the encoded value is higher the importance.\
In one word, ranking.

If the values represent the rank, then we use,
### Ordinal Encoding

It is used to encode categorical data that have an intrinsic order or ranking. In this technique, each category is asssigned a numerical value based on its position in the order. For example, if we have a categorical variable 'education level' with four possible values (high school, college, graduate, post-graduate), we can represent it using ordinal encoding as follows:

1. High School: 1
2. College: 2
3. Graduate: 3
4. Post-Graduate: 4

In [34]:
from sklearn.preprocessing import OrdinalEncoder

In [35]:
df = pd.DataFrame({
    'size': ['small', 'medium', 'large', 'medium', 'small', 'large']
})

In [36]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [37]:
## create an instance of OrdinalEncoder
ord_encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']])

In [38]:
ord_encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [39]:
ord_encoder.transform([['medium']])

d:\Udemy Courses\complete_data_science_machine_learning_dl_nlp_bootcamp\.venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[1.]])

### Target Guided Ordinal Encoding

It is a technique to encode categorical variables based on their relationship with the target variable. This encoding techniques is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

In Target Guided Ordinal Encoding, we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable for that category. This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model.

In [42]:
df = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Tokyo', 'New York', 'Paris'],
    'price': [200, 150, 100, 250, 180, 320]
})

In [43]:
df

       city  price
0  New York    200
1    London    150
2     Paris    100
3     Tokyo    250
4  New York    180
5     Paris    320

In [48]:
mean_price = df.groupby('city')['price'].mean().to_dict()

In [49]:
mean_price

{'London': 150.0, 'New York': 190.0, 'Paris': 210.0, 'Tokyo': 250.0}

In [50]:
df['city_encoded'] = df['city'].map(mean_price)

In [51]:
df

       city  price  city_encoded
0  New York    200         190.0
1    London    150         150.0
2     Paris    100         210.0
3     Tokyo    250         250.0
4  New York    180         190.0
5     Paris    320         210.0

#### Assignment

convert time based on the total bill

In [53]:
sns.load_dataset('tips').head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4